# version: '3.9'


# services:
#   postgres:
#     image: postgres:14-alpine
#     ports:
#       - '5432:5432'
#     container_name: backend_postgres
#     environment:
#       POSTGRES_DB: user_collection
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: P@ssw0rd
#     volumes:
#       - ./data/db:/var/lib/postgresql/data/
  
#   # frontend:
#   #   container_name: demo_frontend
#   #   build:
#   #     context: ./demo-frontend
#   #     dockerfile: Dockerfile

#   #   ports:
#   #     - '3000:3000'

#   #   volumes:
#   #     - ./frontend:/app/frontend

#   #   depends_on:
#   #     - backend

#   backend: 
#     container_name: demo_backend
#     build: 
#       context: ./demo-backend
#       dockerfile: Dockerfile

#     environment:
#       - DB_NAME=user_collection
#       - DB_USER=admin
#       - DB_PASSWORD=P@ssw0rd
#       - DB_PORT=5432

#     ports:
#       - '8000:8000'

#     volumes:
#       - ./backend:/app/backend
    
#     command: >
#             /bin/bash -c "
#                 python manage.py migrate;
#             "

#     depends_on:
#       - postgres

version: '3'

services:
  demo_postgres:
    image: postgres:12.10
    container_name: demo_postgres
    environment:
      POSTGRES_DB: user_collection
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
    networks:
      - local
    command: postgres -c max_prepared_transactions=8
    ports:
      - 5434:5432

  web:
    build: .
    command:  >
      /bin/bash -c "
          python manage.py migrate;
          python manage.py runserver 0.0.0.0:8000;
      "
    volumes:
      - .:/code
    networks:
      - local
    ports:
      - "8000:8000"
    depends_on:
      - demo_postgres

networks:
  local:
    name: demo_local
